spring:
  application:
    name: order
  jpa:
    show-sql: true
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: hx_erp
    password: 123456
    url: jdbc:mysql://127.0.0.1:3306/springCloud?characterEncoding=utf-8&useSSL=false
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka/
label: branchA-edited-1    
einvoice:
  url: http://127.0.0.1:7897/invoice
  token: yufdasiufasfodsao
  validMsg: HENGXIN-CAR-345
